version: '3.8'

services:
  testing-service:
    build:
      context: .
      target: development
    command: yarn dev:server
    ports:
      - "3000:3000"
    volumes:
      - ./:/code:cached
      - /var/run/docker.sock:/var/run/docker.sock
